"""Slashless aliases matching the original Next.js API contract."""

from django.urls import path

from apps.manufacturing.views import (
    AssemblyDetailView,
    AssemblyListCreateView,
    MixingDetailView,
    MixingListCreateView,
    NJPDetailView,
    NJPListCreateView,
)
from apps.commercial.views import (
    BrandDetailView,
    BrandListCreateView,
    CurrencyRateView,
    ProductDetailView,
    ProductFormulaView,
    ProductListCreateView,
    ProductPricingView,
    ProductsByRawMaterialView,
)
from apps.inventory.views import (
    BottleLidDetailView,
    BottleLidListCreateView,
    FinishedGoodsDetailView,
    FinishedGoodsListCreateView,
    InventoryHistoryView,
    LabelDetailView,
    LabelListCreateView,
    LabelValidationView,
    ManualAdjustmentView,
    AdjustStockView,
    LowStockView,
    RawMaterialByCodeView,
    RawMaterialCategoryDetailView,
    RawMaterialCategoryListCreateView,
    RawMaterialDetailView,
    RawMaterialListCreateView,
    SetStockView,
)
urlpatterns = [
    path("brands", BrandListCreateView.as_view()),
    path("brands/<uuid:item_id>", BrandDetailView.as_view()),
    path("products", ProductListCreateView.as_view()),
    path(
        "products/by-raw-material/<uuid:raw_material_id>",
        ProductsByRawMaterialView.as_view(),
    ),
    path("products/<uuid:item_id>", ProductDetailView.as_view()),
    path("products/<uuid:item_id>/formula", ProductFormulaView.as_view()),
    path("raw-materials", RawMaterialListCreateView.as_view()),
    path("raw-materials/low-stock", LowStockView.as_view()),
    path("raw-materials/adjust-stock", AdjustStockView.as_view()),
    path("raw-materials/set-stock", SetStockView.as_view()),
    path("raw-materials/by-code/<str:code>", RawMaterialByCodeView.as_view()),
    path("raw-materials/<uuid:item_id>", RawMaterialDetailView.as_view()),
    path("raw-material-categories", RawMaterialCategoryListCreateView.as_view()),
    path("raw-material-categories/<uuid:item_id>", RawMaterialCategoryDetailView.as_view()),
    path("labels", LabelListCreateView.as_view()),
    path("labels/validate", LabelValidationView.as_view()),
    path("labels/<uuid:item_id>", LabelDetailView.as_view()),
    path("bottles-lids", BottleLidListCreateView.as_view()),
    path("bottles-lids/<uuid:item_id>", BottleLidDetailView.as_view()),
    path("mixing", MixingListCreateView.as_view()),
    path("mixing/<str:item_id>", MixingDetailView.as_view()),
    path("njp", NJPListCreateView.as_view()),
    path("njp/<str:item_id>", NJPDetailView.as_view()),
    path("assembly", AssemblyListCreateView.as_view()),
    path("assembly/<str:item_id>", AssemblyDetailView.as_view()),
    path("product-price-calculator/<uuid:product_id>", ProductPricingView.as_view()),
    path("currency-rate", CurrencyRateView.as_view()),
    path("finished-goods", FinishedGoodsListCreateView.as_view()),
    path("finished-goods/history", InventoryHistoryView.as_view()),
    path("finished-goods/manual-adjustment", ManualAdjustmentView.as_view()),
    path("finished-goods/<uuid:item_id>", FinishedGoodsDetailView.as_view()),
]
