"""Slashless aliases matching the original Next.js API contract."""

from django.urls import path

from apps.batches.views import (
    AssemblyView,
    AssemblyReportListView,
    BatchDetailView,
    BatchListCreateView,
    MixingView,
    MixingReportListView,
    NJPView,
    NJPReportListView,
    StageEndView,
    StageLifecycleUpdateView,
    StageStartView,
    TimelineView,
    ValidateLabelsView,
    ValidateStockView,
)
from apps.brands.views import BrandDetailView, BrandListCreateView
from apps.finance.views import (
    CloseExpenseBookView,
    ExpenseBookBalanceView,
    ExpenseBookDetailView,
    ExpenseBookListCreateView,
    ExpenseDetailView,
    ExpenseListCreateView,
    PullCarryView,
    ReopenExpenseBookView,
)
from apps.hr.views import (
    EmployeeDetailView,
    EmployeeListCreateView,
    EmployeeLoanDetailView,
    EmployeeLoanListCreateView,
    GenerateSalarySheetView,
    LoanWithExpenseView,
    LockSalarySheetView,
    SalarySheetDetailView,
    SalarySheetListCreateView,
    TimeEntryListCreateView,
    WorkEntryDetailView,
    WorkEntryListCreateView,
)
from apps.inventory.views import (
    FinishedGoodByBatchView,
    FinishedGoodsDetailView,
    FinishedGoodsListCreateView,
    InventoryHistoryView,
    ManualAdjustmentView,
)
from apps.labels.views import LabelDetailView, LabelListCreateView, LabelValidationView
from apps.procurement.views import (
    CompanySettingsView,
    PODocumentDetailView,
    PODocumentListCreateView,
    PostPurchaseOrderView,
    PurchaseOrderDetailView,
    PurchaseOrderListCreateView,
    VendorDetailView,
    VendorListCreateView,
)
from apps.products.views import (
    ProductDetailView,
    ProductFormulaView,
    ProductListCreateView,
    ProductsByRawMaterialView,
)
from apps.raw_materials.views import (
    AdjustStockView,
    LowStockView,
    RawMaterialByCodeView,
    RawMaterialCategoryDetailView,
    RawMaterialCategoryListCreateView,
    RawMaterialDetailView,
    RawMaterialListCreateView,
    SetStockView,
)
from apps.reports.views import BatchPricingView


urlpatterns = [
    path("company-settings", CompanySettingsView.as_view()),
    path("brands", BrandListCreateView.as_view()),
    path("brands/<uuid:item_id>", BrandDetailView.as_view()),
    path("products", ProductListCreateView.as_view()),
    path(
        "products/by-raw-material/<uuid:raw_material_id>",
        ProductsByRawMaterialView.as_view(),
    ),
    path("products/<uuid:item_id>", ProductDetailView.as_view()),
    path("products/<uuid:item_id>/formula", ProductFormulaView.as_view()),
    path("raw-materials", RawMaterialListCreateView.as_view()),
    path("raw-materials/low-stock", LowStockView.as_view()),
    path("raw-materials/adjust-stock", AdjustStockView.as_view()),
    path("raw-materials/set-stock", SetStockView.as_view()),
    path("raw-materials/by-code/<str:code>", RawMaterialByCodeView.as_view()),
    path("raw-materials/<uuid:item_id>", RawMaterialDetailView.as_view()),
    path("raw-material-categories", RawMaterialCategoryListCreateView.as_view()),
    path("raw-material-categories/<uuid:item_id>", RawMaterialCategoryDetailView.as_view()),
    path("labels", LabelListCreateView.as_view()),
    path("labels/validate", LabelValidationView.as_view()),
    path("labels/<uuid:item_id>", LabelDetailView.as_view()),
    path("batches", BatchListCreateView.as_view()),
    path("batches/mixing-reports", MixingReportListView.as_view()),
    path("batches/njp-reports", NJPReportListView.as_view()),
    path("batches/assembly-reports", AssemblyReportListView.as_view()),
    path("batches/<uuid:item_id>", BatchDetailView.as_view()),
    path("batches/<uuid:item_id>/validate-stock", ValidateStockView.as_view()),
    path("batches/<uuid:item_id>/validate-labels", ValidateLabelsView.as_view()),
    path("batches/<uuid:item_id>/stages/<str:stage>/start", StageStartView.as_view()),
    path("batches/<uuid:item_id>/stages/<str:stage>/lifecycle", StageLifecycleUpdateView.as_view()),
    path("batches/<uuid:item_id>/stages/<str:stage>/end", StageEndView.as_view()),
    path("batches/<uuid:item_id>/mixing", MixingView.as_view()),
    path("batches/<uuid:item_id>/njp", NJPView.as_view()),
    path("batches/<uuid:item_id>/assembly", AssemblyView.as_view()),
    path("batches/<uuid:item_id>/timeline", TimelineView.as_view()),
    path("batches/<uuid:item_id>/traceability", TimelineView.as_view()),
    path("batches/<uuid:batch_id>/pricing", BatchPricingView.as_view()),
    path("finished-goods", FinishedGoodsListCreateView.as_view()),
    path("finished-goods/history", InventoryHistoryView.as_view()),
    path("finished-goods/manual-adjustment", ManualAdjustmentView.as_view()),
    path("finished-goods/by-batch/<uuid:batch_id>", FinishedGoodByBatchView.as_view()),
    path("finished-goods/<uuid:item_id>", FinishedGoodsDetailView.as_view()),
    path("vendors", VendorListCreateView.as_view()),
    path("vendors/<uuid:item_id>", VendorDetailView.as_view()),
    path("purchase-orders", PurchaseOrderListCreateView.as_view()),
    path("purchase-orders/<uuid:item_id>", PurchaseOrderDetailView.as_view()),
    path("purchase-orders/<uuid:item_id>/post-to-inventory", PostPurchaseOrderView.as_view()),
    path("po-documents", PODocumentListCreateView.as_view()),
    path("po-documents/<uuid:item_id>", PODocumentDetailView.as_view()),
    path("employees", EmployeeListCreateView.as_view()),
    path("employees/<uuid:item_id>", EmployeeDetailView.as_view()),
    path("time-entries", TimeEntryListCreateView.as_view()),
    path("work-entries", WorkEntryListCreateView.as_view()),
    path("work-entries/<uuid:item_id>", WorkEntryDetailView.as_view()),
    path("salary-sheets", SalarySheetListCreateView.as_view()),
    path("salary-sheets/generate", GenerateSalarySheetView.as_view()),
    path("salary-sheets/<uuid:item_id>", SalarySheetDetailView.as_view()),
    path("salary-sheets/<uuid:item_id>/lock", LockSalarySheetView.as_view()),
    path("employee-loans", EmployeeLoanListCreateView.as_view()),
    path("employee-loans/<uuid:item_id>", EmployeeLoanDetailView.as_view()),
    path("employee-loans/with-expense", LoanWithExpenseView.as_view()),
    path("expense-books", ExpenseBookListCreateView.as_view()),
    path("expense-books/<uuid:item_id>", ExpenseBookDetailView.as_view()),
    path("expense-books/<uuid:item_id>/close", CloseExpenseBookView.as_view()),
    path("expense-books/<uuid:item_id>/reopen", ReopenExpenseBookView.as_view()),
    path("expense-books/<uuid:item_id>/balance", ExpenseBookBalanceView.as_view()),
    path("expense-books/<uuid:item_id>/pull-carry", PullCarryView.as_view()),
    path("expenses", ExpenseListCreateView.as_view()),
    path("expenses/<uuid:item_id>", ExpenseDetailView.as_view()),
]
