create table public.mixings (
    id uuid primary key default gen_random_uuid(),
    mixing_number bigint generated by default as identity,
    mixing_code text unique,
    product_id uuid not null references public.products(id) on delete restrict,
    location_id uuid references public.inventory_locations(id) on delete set null,
    location_text text,
    total_kg_in_mixing numeric(18, 6) not null,
    existing_mixed_powder_lot_id uuid references public.inventory_lots(id) on delete restrict,
    existing_mixed_powder_used_kg numeric(18, 6) not null default 0,
    fresh_mixing_required_kg numeric(18, 6) not null,
    calculated_fresh_raw_materials_total_kg numeric(18, 6) not null default 0,
    total_mixed_qty_kg numeric(18, 6) not null,
    output_inventory_item_id uuid references public.inventory_items(id) on delete restrict,
    output_inventory_lot_id uuid references public.inventory_lots(id) on delete restrict,
    status text not null default 'completed',
    remarks text,
    change_reason text,
    version integer not null default 1,
    record_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint mixings_total_positive check (total_kg_in_mixing > 0),
    constraint mixings_existing_non_negative check (existing_mixed_powder_used_kg >= 0),
    constraint mixings_fresh_non_negative check (fresh_mixing_required_kg >= 0),
    constraint mixings_total_rule check (
        total_mixed_qty_kg = total_kg_in_mixing
        and fresh_mixing_required_kg = total_kg_in_mixing - existing_mixed_powder_used_kg
        and existing_mixed_powder_used_kg < total_kg_in_mixing
    ),
    constraint mixings_status_allowed check (
        status in ('draft', 'underprocess', 'completed', 'cancelled')
    )
);

create or replace function public.assign_mixing_code()
returns trigger
language plpgsql
as $$
begin
    if new.mixing_code is null or btrim(new.mixing_code) = '' then
        new.mixing_code := 'MIX-' || lpad(new.mixing_number::text, 4, '0');
    end if;
    return new;
end;
$$;

create trigger mixings_assign_code
before insert on public.mixings
for each row execute function public.assign_mixing_code();

create trigger mixings_set_updated_at
before update on public.mixings
for each row execute function public.set_updated_at();

create table public.mixing_brands (
    id uuid primary key default gen_random_uuid(),
    mixing_id uuid not null references public.mixings(id) on delete cascade,
    brand_id uuid not null references public.brands(id) on delete restrict,
    is_primary boolean not null default false,
    created_at timestamptz not null default now(),
    unique (mixing_id, brand_id)
);

create unique index mixing_brands_one_primary
on public.mixing_brands (mixing_id)
where is_primary;

create index mixing_brands_brand_idx on public.mixing_brands (brand_id);

create table public.mixing_ingredients (
    id uuid primary key default gen_random_uuid(),
    mixing_id uuid not null references public.mixings(id) on delete cascade,
    ingredient_type text not null,
    raw_material_id uuid references public.raw_materials(inventory_item_id) on delete restrict,
    raw_material_lot_id uuid references public.inventory_lots(id) on delete restrict,
    raw_material_name text,
    mg_dose_used numeric(18, 6) not null,
    percent_share numeric(12, 6) not null default 0,
    kg_used numeric(18, 6) not null,
    remarks text,
    sort_order integer not null default 1,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint mixing_ingredients_type_allowed check (
        ingredient_type in ('medicinal', 'non_medicinal')
    ),
    constraint mixing_ingredients_dose_non_negative check (mg_dose_used >= 0),
    constraint mixing_ingredients_kg_non_negative check (kg_used >= 0)
);

create index mixing_ingredients_mixing_idx
on public.mixing_ingredients (mixing_id, ingredient_type, sort_order);

create index mixing_ingredients_rm_idx
on public.mixing_ingredients (raw_material_id);

create table public.mixing_sessions (
    id uuid primary key default gen_random_uuid(),
    mixing_id uuid not null references public.mixings(id) on delete cascade,
    session_date date not null,
    start_time time,
    end_time time,
    remarks text,
    sort_order integer not null default 1,
    created_at timestamptz not null default now()
);

create index mixing_sessions_mixing_date_idx
on public.mixing_sessions (mixing_id, session_date, sort_order);
