create table public.njp_runs (
    id uuid primary key default gen_random_uuid(),
    njp_number bigint generated by default as identity,
    njp_code text unique,
    mixing_id uuid not null references public.mixings(id) on delete restrict,
    input_mixed_powder_lot_id uuid references public.inventory_lots(id) on delete restrict,
    output_capsule_inventory_item_id uuid references public.inventory_items(id) on delete restrict,
    output_capsule_lot_id uuid references public.inventory_lots(id) on delete restrict,
    capsule_size text not null default '00',
    location_id uuid references public.inventory_locations(id) on delete set null,
    location_text text,
    bucket text,
    machine_model text,
    machine_speed text,
    available_mixing_used_kg numeric(18, 6) not null,
    target_fill_weight_mg numeric(18, 6) not null,
    mixing_mg_total numeric(18, 6) not null default 0,
    total_capsules_filled_qty numeric(18, 6) not null,
    rejected_capsules_qty numeric(18, 6) not null default 0,
    net_capsules_qty numeric(18, 6) not null,
    empty_capsule_weight_mg numeric(18, 6) not null default 123,
    total_capsules_produced_kg numeric(18, 6) not null default 0,
    yield_percent numeric(8, 4) not null default 0,
    status text not null default 'underprocess',
    remarks text,
    version integer not null default 1,
    record_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint njp_capsule_size_allowed check (capsule_size in ('0', '00')),
    constraint njp_status_allowed check (status in ('underprocess', 'completed')),
    constraint njp_mixing_used_positive check (available_mixing_used_kg > 0),
    constraint njp_target_weight_positive check (target_fill_weight_mg > 0),
    constraint njp_quantities_non_negative check (
        total_capsules_filled_qty >= 0
        and rejected_capsules_qty >= 0
        and net_capsules_qty >= 0
        and rejected_capsules_qty <= total_capsules_filled_qty
    )
);

create or replace function public.assign_njp_code()
returns trigger
language plpgsql
as $$
begin
    if new.njp_code is null or btrim(new.njp_code) = '' then
        new.njp_code := 'NJP-' || lpad(new.njp_number::text, 4, '0');
    end if;
    return new;
end;
$$;

create trigger njp_runs_assign_code
before insert on public.njp_runs
for each row execute function public.assign_njp_code();

create trigger njp_runs_set_updated_at
before update on public.njp_runs
for each row execute function public.set_updated_at();

create table public.njp_load_checks (
    id uuid primary key default gen_random_uuid(),
    njp_id uuid not null references public.njp_runs(id) on delete cascade,
    check_time timestamptz not null default now(),
    sample_count integer,
    average_weight_mg numeric(18, 6),
    min_weight_mg numeric(18, 6),
    max_weight_mg numeric(18, 6),
    operator_name text,
    remarks text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index njp_load_checks_njp_time_idx
on public.njp_load_checks (njp_id, check_time);

create table public.njp_sessions (
    id uuid primary key default gen_random_uuid(),
    njp_id uuid not null references public.njp_runs(id) on delete cascade,
    session_date date not null,
    start_time time,
    end_time time,
    remarks text,
    sort_order integer not null default 1,
    created_at timestamptz not null default now()
);

create index njp_sessions_njp_date_idx
on public.njp_sessions (njp_id, session_date, sort_order);
