create table public.assemblies (
    id uuid primary key default gen_random_uuid(),
    assembly_number bigint generated by default as identity,
    assembly_code text unique,
    njp_id uuid not null references public.njp_runs(id) on delete restrict,
    input_capsule_lot_id uuid references public.inventory_lots(id) on delete restrict,
    packaging_lot_id uuid references public.inventory_lots(id) on delete restrict,
    location_id uuid references public.inventory_locations(id) on delete set null,
    location_text text,
    box_number text,
    bottle_type text not null default 'capsule',
    bottle_size integer,
    capsule_weight_mg numeric(18, 6) not null default 0,
    capsules_received_qty numeric(18, 6) not null,
    capsules_received_kg numeric(18, 6) not null default 0,
    capsules_per_bottle integer not null,
    total_bottles_made integer not null,
    remaining_capsules_qty numeric(18, 6) not null default 0,
    bottle_cc text,
    filled_bottle_weight text,
    production_date date,
    expiry_date date,
    status text not null default 'underprocess',
    operator_name text,
    comments text,
    version integer not null default 1,
    record_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint assemblies_status_allowed check (status in ('underprocess', 'completed')),
    constraint assemblies_bottle_rule check (
        (bottle_type = 'capsule' and bottle_size in (200, 250, 300))
        or (bottle_type = 'jar' and bottle_size is null)
    ),
    constraint assemblies_qty_rule check (
        capsules_received_qty >= 0
        and capsules_received_kg >= 0
        and capsules_per_bottle > 0
        and total_bottles_made >= 0
        and remaining_capsules_qty >= 0
    )
);

create trigger assemblies_set_updated_at
before update on public.assemblies
for each row execute function public.set_updated_at();

create table public.assembly_brands (
    id uuid primary key default gen_random_uuid(),
    assembly_id uuid not null references public.assemblies(id) on delete cascade,
    brand_id uuid not null references public.brands(id) on delete restrict,
    is_primary boolean not null default false,
    created_at timestamptz not null default now(),
    unique (assembly_id, brand_id)
);

create unique index assembly_brands_one_primary
on public.assembly_brands (assembly_id)
where is_primary;

create table public.assembly_brand_lots (
    id uuid primary key default gen_random_uuid(),
    assembly_id uuid not null references public.assemblies(id) on delete cascade,
    brand_id uuid not null references public.brands(id) on delete restrict,
    finished_good_inventory_item_id uuid references public.inventory_items(id) on delete restrict,
    finished_good_lot_id uuid references public.inventory_lots(id) on delete restrict,
    batch_code text not null,
    bottles_qty integer not null,
    comments text,
    created_at timestamptz not null default now(),
    constraint assembly_brand_lots_bottles_non_negative check (bottles_qty >= 0),
    constraint assembly_brand_lots_batch_not_blank check (btrim(batch_code) <> '')
);

create unique index assembly_brand_lots_brand_batch_unique
on public.assembly_brand_lots (brand_id, batch_code);

create index assembly_brand_lots_assembly_idx
on public.assembly_brand_lots (assembly_id);

create table public.assembly_sessions (
    id uuid primary key default gen_random_uuid(),
    assembly_id uuid not null references public.assemblies(id) on delete cascade,
    session_date date not null,
    start_time time,
    end_time time,
    remarks text,
    sort_order integer not null default 1,
    created_at timestamptz not null default now()
);

create index assembly_sessions_assembly_date_idx
on public.assembly_sessions (assembly_id, session_date, sort_order);

create or replace function public.next_brand_batch_code(p_brand_id uuid)
returns text
language plpgsql
as $$
declare
    v_prefix text;
    v_next integer;
begin
    select code_prefix
    into v_prefix
    from public.brands
    where id = p_brand_id;

    if v_prefix is null or btrim(v_prefix) = '' then
        raise exception 'Brand prefix code is required before creating assembly batch code.';
    end if;

    select coalesce(max(nullif(substring(batch_code from length(v_prefix) + 1), '')::integer), 0) + 1
    into v_next
    from public.assembly_brand_lots
    where brand_id = p_brand_id
      and batch_code ~ ('^' || v_prefix || '[0-9]+$');

    return v_prefix || lpad(v_next::text, 3, '0');
end;
$$;
