-- Vendors (real backend - the table previously only existed in the old,
-- unused supabase/migrations/ directory) + a new "Send Items" outbound
-- inventory feature: recording goods sent to a vendor (Assembly bottles,
-- Raw Material, Encapsulation capsules, Mixing powder, or Labels), deducting
-- the sent quantity from that entity's live inventory balance the same way
-- Assembly deducts from Encapsulation (see 014_...sql for the precedent).

-- ---------------------------------------------------------------------------
-- 1. Vendors
-- ---------------------------------------------------------------------------

create table if not exists public.vendors (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    vendor_code text not null,
    short_code text,
    categories text[] not null default '{}',
    email text,
    phone text,
    whatsapp text,
    country text,
    city text,
    address text,
    website text,
    payment_terms text,
    notes text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint vendors_name_not_blank check (btrim(name) <> ''),
    constraint vendors_categories_valid check (
        categories <@ array[
            'raw_material_supplier', 'bottles_jars', 'lid_supplier',
            'label_supplier', 'logistic', 'manufacturer', 'shop'
        ]::text[]
    )
);

create unique index if not exists vendors_vendor_code_unique on public.vendors (vendor_code);

drop trigger if exists vendors_set_updated_at on public.vendors;
create trigger vendors_set_updated_at
before update on public.vendors
for each row execute function public.set_updated_at();

grant select, insert, update, delete on public.vendors to anon, authenticated;
grant all privileges on public.vendors to service_role;

-- ---------------------------------------------------------------------------
-- 2. Sent Items (goods sent out to a vendor)
-- ---------------------------------------------------------------------------

create table if not exists public.sent_items (
    id uuid primary key default gen_random_uuid(),
    sr_number bigint generated by default as identity,
    vendor_id uuid not null references public.vendors(id) on delete restrict,
    brand_id uuid not null references public.brands(id) on delete restrict,
    item_type text not null,
    source_id uuid not null,
    inventory_item_id uuid not null references public.inventory_items(id) on delete restrict,
    item_name text not null,
    item_code text not null,
    quantity numeric(18, 6) not null,
    sent_at timestamptz not null default now(),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint sent_items_type_allowed check (
        item_type in ('assembly', 'raw_material', 'encapsulation', 'mixing', 'label')
    ),
    constraint sent_items_quantity_positive check (quantity > 0)
);

create index if not exists sent_items_vendor_idx on public.sent_items (vendor_id, sent_at desc);
create index if not exists sent_items_brand_idx on public.sent_items (brand_id, sent_at desc);
create index if not exists sent_items_type_idx on public.sent_items (item_type, brand_id);

drop trigger if exists sent_items_set_updated_at on public.sent_items;
create trigger sent_items_set_updated_at
before update on public.sent_items
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 3. save_sent_item: atomic create/update (consume/restore inventory + write
--    the row in one transaction), mirroring save_assembly in 014_...sql.
--    Python resolves which source table the selected item_type/sourceId
--    points to and hands this function the already-resolved
--    inventoryItemId/itemName/itemCode - this function only does the
--    atomic write + inventory consumption, entity-agnostic.
-- ---------------------------------------------------------------------------

create or replace function public.save_sent_item(p_id uuid, p_payload jsonb)
returns uuid
language plpgsql
as $$
declare
    v_id uuid := coalesce(p_id, gen_random_uuid());
    v_existing public.sent_items;
    v_inventory_item_id uuid := (p_payload->>'inventoryItemId')::uuid;
    v_quantity numeric := (p_payload->>'quantity')::numeric;
    v_remaining numeric;
    v_used numeric;
    v_row record;
begin
    if v_inventory_item_id is null then
        raise exception 'Selected item has no inventory record to send from.';
    end if;
    if v_quantity is null or v_quantity <= 0 then
        raise exception 'Enter a Quantity greater than zero.';
    end if;

    -- Update path: restore whatever this record previously consumed before
    -- validating/consuming the new quantity.
    if p_id is not null then
        select * into v_existing from public.sent_items where id = p_id for update;
        if not found then
            raise exception 'Send record not found';
        end if;

        perform public.apply_inventory_movement(
            v_existing.inventory_item_id, null, null, v_existing.quantity, 'adjust',
            'sent_item', p_id, 'Send Items edit/delete restored inventory',
            '{}'::jsonb, gen_random_uuid()::text
        );
    end if;

    select coalesce(sum(quantity), 0) into v_remaining
    from public.inventory_balances where inventory_item_id = v_inventory_item_id;

    if v_quantity > v_remaining then
        raise exception 'Not enough quantity available. Available: %, required: %.', v_remaining, v_quantity;
    end if;

    v_used := v_quantity;
    for v_row in
        select * from public.inventory_balances
        where inventory_item_id = v_inventory_item_id and quantity > 0
        order by inventory_lot_id nulls last
    loop
        exit when v_used <= 0;
        perform public.apply_inventory_movement(
            v_inventory_item_id, v_row.inventory_lot_id, v_row.location_id,
            -least(v_row.quantity, v_used), 'transfer_out',
            'sent_item', v_id, 'Sent to vendor',
            jsonb_build_object('vendorId', p_payload->>'vendorId'), gen_random_uuid()::text
        );
        v_used := v_used - least(v_row.quantity, v_used);
    end loop;

    if p_id is null then
        insert into public.sent_items (
            id, vendor_id, brand_id, item_type, source_id, inventory_item_id,
            item_name, item_code, quantity, sent_at, notes
        ) values (
            v_id, (p_payload->>'vendorId')::uuid, (p_payload->>'brandId')::uuid,
            p_payload->>'itemType', (p_payload->>'sourceId')::uuid, v_inventory_item_id,
            p_payload->>'itemName', p_payload->>'itemCode', v_quantity,
            coalesce(nullif(p_payload->>'sentAt', '')::timestamptz, now()),
            p_payload->>'notes'
        );
    else
        update public.sent_items set
            vendor_id = (p_payload->>'vendorId')::uuid,
            brand_id = (p_payload->>'brandId')::uuid,
            item_type = p_payload->>'itemType',
            source_id = (p_payload->>'sourceId')::uuid,
            inventory_item_id = v_inventory_item_id,
            item_name = p_payload->>'itemName',
            item_code = p_payload->>'itemCode',
            quantity = v_quantity,
            sent_at = coalesce(nullif(p_payload->>'sentAt', '')::timestamptz, sent_at),
            notes = p_payload->>'notes'
        where id = p_id;
    end if;

    return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. delete_sent_item: restore the consumed quantity, then delete the row.
-- ---------------------------------------------------------------------------

create or replace function public.delete_sent_item(p_id uuid)
returns void
language plpgsql
as $$
declare
    v_existing public.sent_items;
begin
    select * into v_existing from public.sent_items where id = p_id for update;
    if not found then
        raise exception 'Send record not found';
    end if;

    perform public.apply_inventory_movement(
        v_existing.inventory_item_id, null, null, v_existing.quantity, 'adjust',
        'sent_item', p_id, 'Send Items delete restored inventory',
        '{}'::jsonb, gen_random_uuid()::text
    );

    delete from public.sent_items where id = p_id;
end;
$$;

grant select, insert, update, delete on public.sent_items to anon, authenticated;
grant all privileges on public.sent_items to service_role;
grant execute on function public.save_sent_item(uuid, jsonb) to anon, authenticated;
grant execute on function public.delete_sent_item(uuid) to anon, authenticated;
