-- Purchase Order documents (header + line items). The frontend
-- (PurchaseOrdersPage.tsx / PODocumentEditor.tsx) has always shipped fully
-- built against a "/api/po-documents" backend that never existed in this
-- migrations-2 schema - the old supabase/migrations/011_po_documents.sql
-- (pre-Django, pre-restructure) was never ported forward. This creates the
-- real tables, following the same conventions already used elsewhere in
-- this folder: trigger-assigned document number (mirrors
-- assign_mixing_code()/assign_encapsulation_code()), GRANT-only access
-- (no RLS, matching 015_vendors_and_sent_items.sql), reusing the existing
-- public.set_updated_at() trigger function.

create table public.po_documents (
    id uuid primary key default gen_random_uuid(),
    po_number_seq bigint generated by default as identity,
    po_number text unique,
    vendor_id uuid references public.vendors(id) on delete restrict,
    vendor_name text not null default '',
    vendor_address text,
    ship_to_name text not null default '',
    ship_to_address text,
    ship_to_phone text,
    brand_id uuid references public.brands(id) on delete set null,
    po_date date not null default current_date,
    terms_conditions text,
    status text not null default 'draft',
    subtotal numeric(14, 4) not null default 0,
    gst_percent numeric(6, 3) not null default 0,
    others_percent numeric(6, 3) not null default 0,
    shipping_percent numeric(6, 3) not null default 0,
    grand_total numeric(14, 4) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint po_documents_status_valid check (
        status in ('draft', 'sent', 'received', 'canceled')
    ),
    constraint po_documents_percents_non_negative check (
        gst_percent >= 0 and others_percent >= 0 and shipping_percent >= 0
    )
);

create index po_documents_vendor_id_idx on public.po_documents (vendor_id);
create index po_documents_brand_id_idx on public.po_documents (brand_id);
create index po_documents_status_idx on public.po_documents (status);

create or replace function public.assign_po_number()
returns trigger
language plpgsql
as $$
begin
    if new.po_number is null or btrim(new.po_number) = '' then
        new.po_number := 'PO-' || lpad(new.po_number_seq::text, 4, '0');
    end if;
    return new;
end;
$$;

create trigger po_documents_assign_number
before insert on public.po_documents
for each row execute function public.assign_po_number();

create trigger po_documents_set_updated_at
before update on public.po_documents
for each row execute function public.set_updated_at();

create table public.po_document_items (
    id uuid primary key default gen_random_uuid(),
    po_document_id uuid not null references public.po_documents(id) on delete cascade,
    sr integer not null,
    order_type text not null default 'raw_material',
    -- Polymorphic reference (raw_materials/labels/products/bottles_lids
    -- depending on order_type) - no FK, matching the original design and
    -- how the frontend already treats this field for the 'custom' type
    -- (no backing row at all).
    item_id uuid,
    item_name text not null default '',
    quantity numeric(14, 4) not null default 0,
    unit_price numeric(14, 4),
    total_price numeric(14, 4),
    created_at timestamptz not null default now(),
    constraint po_document_items_order_type_valid check (
        order_type in ('raw_material', 'label', 'product', 'bottles_lids', 'custom')
    ),
    constraint po_document_items_quantity_non_negative check (quantity >= 0),
    constraint po_document_items_unit_price_non_negative check (
        unit_price is null or unit_price >= 0
    ),
    constraint po_document_items_total_price_non_negative check (
        total_price is null or total_price >= 0
    )
);

create index po_document_items_doc_idx on public.po_document_items (po_document_id);

grant select, insert, update, delete on public.po_documents to anon, authenticated;
grant all privileges on public.po_documents to service_role;
grant select, insert, update, delete on public.po_document_items to anon, authenticated;
grant all privileges on public.po_document_items to service_role;
