-- Request to Quote documents (header + line items). Structurally a clone of
-- po_documents/po_document_items (024_po_documents.sql) for a document sent
-- to a vendor asking them to quote prices, rather than a firm order:
--   - no gst_percent / others_percent / shipping_percent / grand_total
--     (those only apply once an order is placed, not at the quote-request stage)
--   - unit_price and total_price stay optional (the vendor hasn't quoted yet)
--   - quantity stays required, same vendor relationship as po_documents

create table public.request_to_quote_documents (
    id uuid primary key default gen_random_uuid(),
    rtq_number_seq bigint generated by default as identity,
    rtq_number text unique,
    vendor_id uuid references public.vendors(id) on delete restrict,
    vendor_name text not null default '',
    vendor_address text,
    ship_to_name text not null default '',
    ship_to_address text,
    ship_to_phone text,
    brand_id uuid references public.brands(id) on delete set null,
    rtq_date date not null default current_date,
    terms_conditions text,
    status text not null default 'draft',
    subtotal numeric(14, 4) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint request_to_quote_documents_status_valid check (
        status in ('draft', 'sent', 'received', 'canceled')
    )
);

create index request_to_quote_documents_vendor_id_idx on public.request_to_quote_documents (vendor_id);
create index request_to_quote_documents_brand_id_idx on public.request_to_quote_documents (brand_id);
create index request_to_quote_documents_status_idx on public.request_to_quote_documents (status);

create or replace function public.assign_rtq_number()
returns trigger
language plpgsql
as $$
begin
    if new.rtq_number is null or btrim(new.rtq_number) = '' then
        new.rtq_number := 'RTQ-' || lpad(new.rtq_number_seq::text, 4, '0');
    end if;
    return new;
end;
$$;

create trigger request_to_quote_documents_assign_number
before insert on public.request_to_quote_documents
for each row execute function public.assign_rtq_number();

create trigger request_to_quote_documents_set_updated_at
before update on public.request_to_quote_documents
for each row execute function public.set_updated_at();

create table public.request_to_quote_document_items (
    id uuid primary key default gen_random_uuid(),
    request_to_quote_document_id uuid not null references public.request_to_quote_documents(id) on delete cascade,
    sr integer not null,
    order_type text not null default 'raw_material',
    -- Polymorphic reference (raw_materials/labels/products/bottles_lids
    -- depending on order_type) - no FK, matching po_document_items.
    item_id uuid,
    item_name text not null default '',
    quantity numeric(14, 4) not null default 0,
    unit_price numeric(14, 4),
    total_price numeric(14, 4),
    created_at timestamptz not null default now(),
    constraint request_to_quote_document_items_order_type_valid check (
        order_type in ('raw_material', 'label', 'product', 'bottles_lids', 'custom')
    ),
    constraint request_to_quote_document_items_quantity_non_negative check (quantity >= 0),
    constraint request_to_quote_document_items_unit_price_non_negative check (
        unit_price is null or unit_price >= 0
    ),
    constraint request_to_quote_document_items_total_price_non_negative check (
        total_price is null or total_price >= 0
    )
);

create index request_to_quote_document_items_doc_idx on public.request_to_quote_document_items (request_to_quote_document_id);

grant select, insert, update, delete on public.request_to_quote_documents to anon, authenticated;
grant all privileges on public.request_to_quote_documents to service_role;
grant select, insert, update, delete on public.request_to_quote_document_items to anon, authenticated;
grant all privileges on public.request_to_quote_document_items to service_role;
