-- Adds the two missing steps in the procurement pipeline:
--   Request to Quote -> Quote -> Purchase Order -> Invoice
--
-- Quote (one per Request to Quote) and Invoice (one per Purchase Order) are
-- deliberately minimal: a brand-prefixed code, a single attached file (the
-- vendor's quote/invoice document, stored in Supabase Storage), and free-text
-- comments. They reference their parent by number (rtq_number / po_number),
-- not by row id, the same "polymorphic, no FK" convention already used by
-- po_document_items.item_id - RTQ/PO rows are versioned (multiple rows can
-- share the same number), so a number-based soft reference survives the
-- parent being edited into a new version without going stale.
--
-- Numbering reuses the exact per-brand-prefix scheme RTQ/PO already use
-- (assign_rtq_number / assign_po_number in 026/029): same brands.rtq_prefix
-- column, same advisory-lock + regex-scan pattern, just a different number
-- segment ("-Q-" / "-Inv-" instead of "-RTQ-" / "-PO-"), giving
-- BOR-Q-001 / BOR-Inv-001.

create table public.quotes (
    id uuid primary key default gen_random_uuid(),
    quote_number_seq bigint generated by default as identity,
    quote_number text,
    rtq_number text not null,
    brand_id uuid references public.brands(id) on delete set null,
    file_name text,
    file_path text,
    file_size bigint,
    file_type text,
    comments text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint quotes_rtq_number_unique unique (rtq_number)
);

create index quotes_rtq_number_idx on public.quotes (rtq_number);
create index quotes_brand_id_idx on public.quotes (brand_id);

create or replace function public.assign_quote_number()
returns trigger
language plpgsql
as $$
declare
    v_prefix text;
    v_next integer;
begin
    if new.quote_number is not null and btrim(new.quote_number) <> '' then
        return new;
    end if;

    if new.brand_id is null then
        raise exception 'Select a brand before saving a Quote - its Quote number depends on the brand.';
    end if;

    perform pg_advisory_xact_lock(hashtextextended('quote_number:' || new.brand_id::text, 0));

    select rtq_prefix into v_prefix from public.brands where id = new.brand_id;
    if v_prefix is null or btrim(v_prefix) = '' then
        update public.brands
        set rtq_prefix = public.compute_brand_rtq_prefix(name)
        where id = new.brand_id
        returning rtq_prefix into v_prefix;
    end if;

    select coalesce(
        max(nullif(substring(quote_number from '-Q-([0-9]+)$'), '')::integer),
        0
    ) + 1
    into v_next
    from public.quotes
    where quote_number ~ ('^' || v_prefix || '-Q-[0-9]+$');

    new.quote_number := v_prefix || '-Q-' || lpad(v_next::text, 3, '0');
    return new;
end;
$$;

create trigger quotes_assign_number
before insert on public.quotes
for each row execute function public.assign_quote_number();

create trigger quotes_set_updated_at
before update on public.quotes
for each row execute function public.set_updated_at();

create table public.invoices (
    id uuid primary key default gen_random_uuid(),
    invoice_number_seq bigint generated by default as identity,
    invoice_number text,
    po_number text not null,
    brand_id uuid references public.brands(id) on delete set null,
    file_name text,
    file_path text,
    file_size bigint,
    file_type text,
    comments text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint invoices_po_number_unique unique (po_number)
);

create index invoices_po_number_idx on public.invoices (po_number);
create index invoices_brand_id_idx on public.invoices (brand_id);

create or replace function public.assign_invoice_number()
returns trigger
language plpgsql
as $$
declare
    v_prefix text;
    v_next integer;
begin
    if new.invoice_number is not null and btrim(new.invoice_number) <> '' then
        return new;
    end if;

    if new.brand_id is null then
        raise exception 'Select a brand before saving an Invoice - its Invoice number depends on the brand.';
    end if;

    perform pg_advisory_xact_lock(hashtextextended('invoice_number:' || new.brand_id::text, 0));

    select rtq_prefix into v_prefix from public.brands where id = new.brand_id;
    if v_prefix is null or btrim(v_prefix) = '' then
        update public.brands
        set rtq_prefix = public.compute_brand_rtq_prefix(name)
        where id = new.brand_id
        returning rtq_prefix into v_prefix;
    end if;

    select coalesce(
        max(nullif(substring(invoice_number from '-Inv-([0-9]+)$'), '')::integer),
        0
    ) + 1
    into v_next
    from public.invoices
    where invoice_number ~ ('^' || v_prefix || '-Inv-[0-9]+$');

    new.invoice_number := v_prefix || '-Inv-' || lpad(v_next::text, 3, '0');
    return new;
end;
$$;

create trigger invoices_assign_number
before insert on public.invoices
for each row execute function public.assign_invoice_number();

create trigger invoices_set_updated_at
before update on public.invoices
for each row execute function public.set_updated_at();

grant select, insert, update, delete on public.quotes to anon, authenticated;
grant all privileges on public.quotes to service_role;
grant select, insert, update, delete on public.invoices to anon, authenticated;
grant all privileges on public.invoices to service_role;

-- po_documents records which RTQ/Quote it was created from, so the PO
-- editor/list can show the chain and so the RTQ picker (in the PO creation
-- form) can tell which RTQs already have a Purchase Order. Nullable: ad-hoc
-- POs created without going through an RTQ keep working unchanged.
alter table public.po_documents
    add column if not exists rtq_number text,
    add column if not exists quote_number text;

create index if not exists po_documents_rtq_number_idx on public.po_documents (rtq_number);
