-- ============================================================================
-- 003_batch_workflow.sql
-- Batches and manufacturing reports.
-- ============================================================================

CREATE TABLE IF NOT EXISTS batches (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id            uuid NOT NULL REFERENCES brands(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  brand_name          text NOT NULL,
  brand_code_prefix   text NOT NULL,
  batch_code          text NOT NULL,
  product_id          uuid NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  product_name        text NOT NULL,
  dosage_form         dosage_form NOT NULL,
  units_per_container integer,
  container_count     integer NOT NULL DEFAULT 0,
  total_units         integer,
  notes               text NOT NULL DEFAULT '',
  status              batch_status NOT NULL DEFAULT 'mixingPending',
  has_mixing          boolean NOT NULL DEFAULT false,
  has_njp             boolean NOT NULL DEFAULT false,
  has_assembly        boolean NOT NULL DEFAULT false,
  inventory_deducted  boolean NOT NULL DEFAULT false,
  created_by          text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT batches_batch_code_not_blank CHECK (length(btrim(batch_code)) > 0),
  CONSTRAINT batches_container_count_nonnegative CHECK (container_count >= 0),
  CONSTRAINT batches_units_per_container_positive CHECK (units_per_container IS NULL OR units_per_container > 0),
  CONSTRAINT batches_total_units_nonnegative CHECK (total_units IS NULL OR total_units >= 0)
);

CREATE TABLE IF NOT EXISTS mixing_reports (
  id                            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id                      uuid NOT NULL REFERENCES batches(id) ON UPDATE CASCADE ON DELETE CASCADE,
  brand_id                      uuid NOT NULL REFERENCES brands(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  product_id                    uuid NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  batch_code                    text,
  brand_name                    text,
  product_name                  text,
  mixing_date                   bigint,
  mixed_powder_name             text,
  mixed_powder_qty_kg           numeric(12,4),
  total_formula_qty_kg          numeric(12,4),
  total_mixed_qty_kg            numeric(12,4),
  existing_mixed_powder_used_kg numeric(12,4),
  rm_usage                      jsonb NOT NULL DEFAULT '[]'::jsonb,
  non_med_usage                 jsonb NOT NULL DEFAULT '[]'::jsonb,
  mixing_dates                  text[] NOT NULL DEFAULT '{}',
  mixing_notes                  text NOT NULL DEFAULT '',
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_at                    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mixing_reports_rm_usage_is_array CHECK (jsonb_typeof(rm_usage) = 'array'),
  CONSTRAINT mixing_reports_non_med_usage_is_array CHECK (jsonb_typeof(non_med_usage) = 'array'),
  CONSTRAINT mixing_reports_mixed_powder_qty_nonnegative CHECK (mixed_powder_qty_kg IS NULL OR mixed_powder_qty_kg >= 0),
  CONSTRAINT mixing_reports_total_formula_qty_nonnegative CHECK (total_formula_qty_kg IS NULL OR total_formula_qty_kg >= 0),
  CONSTRAINT mixing_reports_total_mixed_qty_nonnegative CHECK (total_mixed_qty_kg IS NULL OR total_mixed_qty_kg >= 0),
  CONSTRAINT mixing_reports_existing_powder_qty_nonnegative CHECK (existing_mixed_powder_used_kg IS NULL OR existing_mixed_powder_used_kg >= 0)
);

CREATE TABLE IF NOT EXISTS njp_reports (
  id                         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id                   uuid NOT NULL REFERENCES batches(id) ON UPDATE CASCADE ON DELETE CASCADE,
  brand_id                   uuid NOT NULL REFERENCES brands(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  product_id                 uuid NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  batch_code                 text,
  brand_name                 text,
  product_name               text,
  njp_code                   text,
  lot_number                 text,
  capsule_size               text,
  machine_model              text,
  machine_speed              text,
  raw_material_received_kg   numeric(12,4),
  target_fill_weight_mg      numeric(12,4),
  total_capsules_produced_kg numeric(12,4),
  total_capsules_filled_qty  integer,
  rejected_capsules_qty      integer,
  temperature_c              numeric(8,2),
  temperature_f              numeric(8,2),
  humidity_percent           numeric(8,2),
  duster_check               boolean NOT NULL DEFAULT false,
  vacuum_check               boolean NOT NULL DEFAULT false,
  yield_percent              numeric(8,4),
  start_date                 bigint,
  start_time                 text,
  end_time                   text,
  production_date            bigint,
  load_checks                jsonb NOT NULL DEFAULT '[]'::jsonb,
  remarks                    text,
  operator_name              text,
  capsule_data               jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at                 timestamptz NOT NULL DEFAULT now(),
  updated_at                 timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT njp_reports_load_checks_is_array CHECK (jsonb_typeof(load_checks) = 'array'),
  CONSTRAINT njp_reports_capsule_data_is_object CHECK (jsonb_typeof(capsule_data) = 'object'),
  CONSTRAINT njp_reports_raw_material_received_nonnegative CHECK (raw_material_received_kg IS NULL OR raw_material_received_kg >= 0),
  CONSTRAINT njp_reports_target_fill_weight_nonnegative CHECK (target_fill_weight_mg IS NULL OR target_fill_weight_mg >= 0),
  CONSTRAINT njp_reports_total_capsules_kg_nonnegative CHECK (total_capsules_produced_kg IS NULL OR total_capsules_produced_kg >= 0),
  CONSTRAINT njp_reports_filled_qty_nonnegative CHECK (total_capsules_filled_qty IS NULL OR total_capsules_filled_qty >= 0),
  CONSTRAINT njp_reports_rejected_qty_nonnegative CHECK (rejected_capsules_qty IS NULL OR rejected_capsules_qty >= 0),
  CONSTRAINT njp_reports_humidity_range CHECK (humidity_percent IS NULL OR humidity_percent BETWEEN 0 AND 100),
  CONSTRAINT njp_reports_yield_range CHECK (yield_percent IS NULL OR yield_percent BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS assembly_reports (
  id                                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id                          uuid NOT NULL REFERENCES batches(id) ON UPDATE CASCADE ON DELETE CASCADE,
  brand_id                          uuid NOT NULL REFERENCES brands(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  product_id                        uuid NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  batch_code                        text,
  brand_name                        text,
  product_name                      text,
  capsule_weight                    numeric(10,4),
  capsule_weight_mg                 numeric(10,4),
  filled_bottle_weight              numeric(10,4),
  capsules_received_kg              numeric(12,4),
  capsules_received_qty             integer,
  production_date                   bigint,
  expiry_date                       bigint,
  total_bottles_made                integer,
  bottle_cc                         numeric(10,2),
  capsules_per_bottle               integer,
  received_capsule_bucket_number    text,
  received_capsules_production_date bigint,
  operator_name                     text,
  notes                             text,
  final_quantities                  jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at                        timestamptz NOT NULL DEFAULT now(),
  updated_at                        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT assembly_reports_final_quantities_is_object CHECK (jsonb_typeof(final_quantities) = 'object'),
  CONSTRAINT assembly_reports_capsule_weight_nonnegative CHECK (capsule_weight IS NULL OR capsule_weight >= 0),
  CONSTRAINT assembly_reports_capsule_weight_mg_nonnegative CHECK (capsule_weight_mg IS NULL OR capsule_weight_mg >= 0),
  CONSTRAINT assembly_reports_filled_bottle_weight_nonnegative CHECK (filled_bottle_weight IS NULL OR filled_bottle_weight >= 0),
  CONSTRAINT assembly_reports_capsules_received_kg_nonnegative CHECK (capsules_received_kg IS NULL OR capsules_received_kg >= 0),
  CONSTRAINT assembly_reports_capsules_received_qty_nonnegative CHECK (capsules_received_qty IS NULL OR capsules_received_qty >= 0),
  CONSTRAINT assembly_reports_total_bottles_nonnegative CHECK (total_bottles_made IS NULL OR total_bottles_made >= 0),
  CONSTRAINT assembly_reports_bottle_cc_nonnegative CHECK (bottle_cc IS NULL OR bottle_cc >= 0),
  CONSTRAINT assembly_reports_capsules_per_bottle_nonnegative CHECK (capsules_per_bottle IS NULL OR capsules_per_bottle >= 0)
);
